-- Supabase schema alignment for the refactored Maize Disease Classifier app.
-- Run this in the Supabase SQL Editor.
--
-- What this script does:
-- 1. Creates required tables when missing.
-- 2. Adds missing columns, defaults, indexes, and foreign keys.
-- 3. Safely converts key columns to UUID when possible.
-- 4. Raises a clear error if existing ID values are not valid UUIDs.

begin;

create schema if not exists public;

create extension if not exists pgcrypto;

create table if not exists public.users (
    id uuid primary key,
    email text not null,
    username text not null,
    full_name text,
    avatar_url text,
    is_admin boolean not null default false,
    is_active boolean not null default true,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    last_login timestamptz
);

create table if not exists public.user_settings (
    id bigint generated by default as identity primary key,
    user_id uuid not null unique
);

create table if not exists public.predictions (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    image_name text not null,
    image_url text,
    prediction text not null,
    confidence double precision not null,
    probabilities_json text not null,
    processing_time double precision,
    ip_address text,
    user_agent text,
    created_at timestamptz default now()
);

create table if not exists public.system_logs (
    id bigint generated by default as identity primary key,
    level text not null,
    created_at timestamptz default now()
);

create table if not exists public.feedback (
    id bigint generated by default as identity primary key,
    user_id uuid,
    name text,
    email text,
    category text,
    message text not null,
    status text not null default 'new',
    admin_response text,
    responded_by uuid,
    responded_at timestamptz,
    created_at timestamptz default now()
);

alter table public.users add column if not exists email text;
alter table public.users add column if not exists username text;
alter table public.users add column if not exists full_name text;
alter table public.users add column if not exists avatar_url text;
alter table public.users add column if not exists is_admin boolean default false;
alter table public.users add column if not exists is_active boolean default true;
alter table public.users add column if not exists created_at timestamptz default now();
alter table public.users add column if not exists updated_at timestamptz default now();
alter table public.users add column if not exists last_login timestamptz;

alter table public.user_settings add column if not exists user_id uuid;

alter table public.predictions add column if not exists user_id uuid;
alter table public.predictions add column if not exists image_name text;
alter table public.predictions add column if not exists image_url text;
alter table public.predictions add column if not exists prediction text;
alter table public.predictions add column if not exists confidence double precision;
alter table public.predictions add column if not exists probabilities_json text;
alter table public.predictions add column if not exists processing_time double precision;
alter table public.predictions add column if not exists ip_address text;
alter table public.predictions add column if not exists user_agent text;
alter table public.predictions add column if not exists created_at timestamptz default now();

alter table public.system_logs add column if not exists level text;
alter table public.system_logs add column if not exists created_at timestamptz default now();

alter table public.feedback add column if not exists user_id uuid;
alter table public.feedback add column if not exists name text;
alter table public.feedback add column if not exists email text;
alter table public.feedback add column if not exists category text;
alter table public.feedback add column if not exists message text;
alter table public.feedback add column if not exists status text;
alter table public.feedback add column if not exists admin_response text;
alter table public.feedback add column if not exists responded_by uuid;
alter table public.feedback add column if not exists responded_at timestamptz;
alter table public.feedback add column if not exists created_at timestamptz default now();

do $$
declare
    invalid_count bigint;
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'users'
          and column_name = 'id'
          and udt_name <> 'uuid'
    ) then
        execute $sql$
            select count(*)
            from public.users
            where id is null
               or btrim(id::text) = ''
               or id::text !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        $sql$
        into invalid_count;

        if invalid_count > 0 then
            raise exception 'Cannot convert public.users.id to uuid. % row(s) contain non-UUID values.', invalid_count;
        end if;

        alter table public.users
            alter column id type uuid
            using id::text::uuid;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'user_settings'
          and column_name = 'user_id'
          and udt_name <> 'uuid'
    ) then
        execute $sql$
            select count(*)
            from public.user_settings
            where user_id is not null
              and (
                    btrim(user_id::text) = ''
                 or user_id::text !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
              )
        $sql$
        into invalid_count;

        if invalid_count > 0 then
            raise exception 'Cannot convert public.user_settings.user_id to uuid. % row(s) contain non-UUID values.', invalid_count;
        end if;

        alter table public.user_settings
            alter column user_id type uuid
            using nullif(user_id::text, '')::uuid;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'predictions'
          and column_name = 'user_id'
          and udt_name <> 'uuid'
    ) then
        execute $sql$
            select count(*)
            from public.predictions
            where user_id is not null
              and (
                    btrim(user_id::text) = ''
                 or user_id::text !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
              )
        $sql$
        into invalid_count;

        if invalid_count > 0 then
            raise exception 'Cannot convert public.predictions.user_id to uuid. % row(s) contain non-UUID values.', invalid_count;
        end if;

        alter table public.predictions
            alter column user_id type uuid
            using nullif(user_id::text, '')::uuid;
    end if;
end $$;

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'users'
          and column_name = 'created_at'
          and data_type <> 'timestamp with time zone'
    ) then
        alter table public.users
            alter column created_at type timestamptz
            using created_at::timestamptz;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'users'
          and column_name = 'updated_at'
          and data_type <> 'timestamp with time zone'
    ) then
        alter table public.users
            alter column updated_at type timestamptz
            using updated_at::timestamptz;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'users'
          and column_name = 'last_login'
          and data_type <> 'timestamp with time zone'
    ) then
        alter table public.users
            alter column last_login type timestamptz
            using last_login::timestamptz;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'predictions'
          and column_name = 'created_at'
          and data_type <> 'timestamp with time zone'
    ) then
        alter table public.predictions
            alter column created_at type timestamptz
            using created_at::timestamptz;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'system_logs'
          and column_name = 'created_at'
          and data_type <> 'timestamp with time zone'
    ) then
        alter table public.system_logs
            alter column created_at type timestamptz
            using created_at::timestamptz;
    end if;
end $$;

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'predictions'
          and column_name = 'confidence'
          and data_type <> 'double precision'
    ) then
        alter table public.predictions
            alter column confidence type double precision
            using confidence::double precision;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'predictions'
          and column_name = 'processing_time'
          and data_type <> 'double precision'
    ) then
        alter table public.predictions
            alter column processing_time type double precision
            using processing_time::double precision;
    end if;
end $$;

update public.users
set is_admin = false
where is_admin is null;

update public.users
set is_active = true
where is_active is null;

update public.users
set created_at = now()
where created_at is null;

update public.users
set updated_at = now()
where updated_at is null;

update public.predictions
set created_at = now()
where created_at is null;

update public.feedback
set created_at = now()
where created_at is null;

update public.feedback
set status = 'new'
where status is null;

alter table public.users alter column email set not null;
alter table public.users alter column username set not null;
alter table public.users alter column is_admin set not null;
alter table public.users alter column is_active set not null;

alter table public.users alter column is_admin set default false;
alter table public.users alter column is_active set default true;
alter table public.users alter column created_at set default now();
alter table public.users alter column updated_at set default now();

alter table public.user_settings alter column user_id set not null;

alter table public.predictions alter column user_id set not null;
alter table public.predictions alter column image_name set not null;
alter table public.predictions alter column prediction set not null;
alter table public.predictions alter column confidence set not null;
alter table public.predictions alter column probabilities_json set not null;
alter table public.predictions alter column created_at set default now();

alter table public.system_logs alter column level set not null;
alter table public.system_logs alter column created_at set default now();

alter table public.feedback alter column message set not null;
alter table public.feedback alter column status set not null;
alter table public.feedback alter column status set default 'new';
alter table public.feedback alter column created_at set default now();

create unique index if not exists users_email_key on public.users (email);
create unique index if not exists users_username_key on public.users (username);
create unique index if not exists user_settings_user_id_key on public.user_settings (user_id);
create index if not exists predictions_user_id_idx on public.predictions (user_id);
create index if not exists predictions_created_at_idx on public.predictions (created_at desc);
create index if not exists predictions_user_created_idx on public.predictions (user_id, created_at desc);
create index if not exists system_logs_level_created_idx on public.system_logs (level, created_at desc);
create index if not exists feedback_created_at_idx on public.feedback (created_at desc);
create index if not exists feedback_user_id_idx on public.feedback (user_id);
create index if not exists feedback_status_created_idx on public.feedback (status, created_at desc);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'user_settings_user_id_fkey'
          and conrelid = 'public.user_settings'::regclass
    ) then
        alter table public.user_settings
            add constraint user_settings_user_id_fkey
            foreign key (user_id)
            references public.users(id)
            on delete cascade;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'predictions_user_id_fkey'
          and conrelid = 'public.predictions'::regclass
    ) then
        alter table public.predictions
            add constraint predictions_user_id_fkey
            foreign key (user_id)
            references public.users(id)
            on delete cascade;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'feedback_user_id_fkey'
          and conrelid = 'public.feedback'::regclass
    ) then
        alter table public.feedback
            add constraint feedback_user_id_fkey
            foreign key (user_id)
            references public.users(id)
            on delete set null;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'feedback_responded_by_fkey'
          and conrelid = 'public.feedback'::regclass
    ) then
        alter table public.feedback
            add constraint feedback_responded_by_fkey
            foreign key (responded_by)
            references public.users(id)
            on delete set null;
    end if;
end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

do $$
begin
    if not exists (
        select 1
        from pg_trigger
        where tgname = 'users_set_updated_at'
    ) then
        create trigger users_set_updated_at
        before update on public.users
        for each row
        execute function public.set_updated_at();
    end if;
end $$;

do $$
begin
    if exists (
        select 1
        from information_schema.tables
        where table_schema = 'auth'
          and table_name = 'users'
    )
    and not exists (
        select 1
        from pg_constraint
        where conname = 'users_id_auth_fkey'
          and conrelid = 'public.users'::regclass
    ) then
        begin
            alter table public.users
                add constraint users_id_auth_fkey
                foreign key (id)
                references auth.users(id)
                on delete cascade;
        exception
            when foreign_key_violation then
                raise notice 'Skipped users_id_auth_fkey because some public.users rows do not exist in auth.users.';
        end;
    end if;
end $$;

commit;
